Accordion:
primait/pyxis-npm pull request #11
Opened 2019-07-12 14:16 UTC by kioan000

- Single accordion don't have visible border bottom when closed

Accordion Group:
- Accordion in accordion group have separation borders (all except last)

Button:
- Adjacent buttons doesn't have default margin anymore, use button group instead
- `a-btn--primary` now have the same height of other buttons (invisible border)
- fixed margin in case of icon due to a duplicated margin setting

Button Group:
- Buttons in button group have margin
- All flex justify modificators
- New specific `m-btnGroup--coverFluid` modificator that allow inner buttons to cover it fully and as much as possible equally growing. Margins are supported until 4 buttons

Utils:
- New `withNElements(selector, n)` mixin that given a selector and a number generates a class that applies only if there are N child elements with that selector
- Added `space-evenly` as justify helper

2019-07-12 14:35 UTC, kioan000 commented
- [ ] `m-accordionGroup`
- [ ] `m-btnGroup` e btn liquidi
- [ ] correzione della classe `.a-btn--smallOnBreakpointXSmall` (attualmente ha una mq min-width e una max-width, dovrebbe avere solo la max-width)
- [ ] correzione del link `a-link--standalone` con freccia che si sovrappone al testo in caso di testo molto lungo
- [ ] correzione del link `a-link--standalone` con problema di allineamento verticale delle freccia

2019-07-15 12:44 UTC, alessiosantangelo requested changes
Due cavolatine da eliminare e un paio di refusi

2019-07-15 12:44 UTC, alessiosantangelo commented on src/scss/02_atoms/_accordion.scss
> +  }
Spazio

2019-07-15 12:44 UTC, alessiosantangelo commented on src/scss/02_atoms/_accordion.scss
> +  .m-group--dark & {
Cancella la classe `m-group` e tutti i suoi riferimenti. Credo sia un refuso.

2019-07-15 12:44 UTC, alessiosantangelo commented on src/scss/03_molecules/_accordionGroup.scss
> +  .a-accordion:not(:last-child) {
`.m-accordionGroup .a-accordion:not(:last-child) .a-accordion__toggle {`

`.m-accordionGroup .a-accordion.a-accordion--dark:not(:last-child) .a-accordion__toggle {`

2019-07-15 12:44 UTC, alessiosantangelo commented on src/scss/03_molecules/_buttonGroup.scss
>  .m-btnGroup.m-btnGroup--left {
Questi si possono rimuovere.

2019-07-15 12:44 UTC, alessiosantangelo commented on src/scss/03_molecules/_buttonGroup.scss
> +  .a-btn {
`.m-btnGroup.m-btnGroup--coverFluid .a-btn`

2019-07-15 12:44 UTC, alessiosantangelo commented on src/scss/03_molecules/_buttonGroup.scss
> +  }
A capo

2019-07-15 12:44 UTC, alessiosantangelo commented on src/scss/03_molecules/_buttonGroup.scss
> +    &:nth-child(1), &:nth-child(3) {
Manda sempre a capo dopo `,`

2019-07-15 13:32 UTC, alessiosantangelo approved these changes

2019-07-15 13:33 UTC, merged