Autocomplete with server
primait/pyxis-npm pull request #42
Opened 2020-06-22 15:25 UTC by Gsciarra

Ho aggiunto la classe .form-autocomplete__spinner-icon per mostrare uno spinner nel componente Autocomplete durante la richiesta al server.

2020-06-22 15:39 UTC, alessiosantangelo requested changes

2020-06-22 15:39 UTC, alessiosantangelo commented on src/scss/02_atoms/form/_autocomplete.scss
> +    border-style: solid;
Qui usa pure lo shorthand `border: 1px solid transparent` (mi pare)

2020-06-22 15:39 UTC, alessiosantangelo commented on src/scss/02_atoms/form/_autocomplete.scss
> +  right: rem(13px);
Questi 24px e 13px meglio se messi sotto variabile (vedi `autocompleteConfig`)

2020-06-22 15:39 UTC, alessiosantangelo commented on src/scss/02_atoms/form/_autocomplete.scss
> +@keyframes animateSpinner {
Di solito il `keyframe` lo definiamo nello scope della regola che lo utilizza se non è condiviso con altre regole

2020-06-22 16:14 UTC, francescophra requested changes

2020-06-22 16:14 UTC, francescophra commented on src/scss/02_atoms/form/_autocomplete.scss
> +.form-autocomplete__spinner-icon {
Una cazzatina, uniformerei il selettore e il nome dell'animazione col nome dell'icona loader. Sarebbe meglio avere `.form-autocomplete__loader-icon` e `@keyframe animateLoader`.

2020-06-23 08:51 UTC, Gsciarra commented on src/scss/02_atoms/form/_autocomplete.scss
> +    border-style: solid;
Chiedo venia, mi sono accorto che quelle regole sono superflue, le ho semplicemente rimosse.

2020-06-23 09:10 UTC, alessiosantangelo approved these changes
LGTM

2020-06-23 10:22 UTC, francescophra commented on src/scss/02_atoms/form/_autocomplete.scss
> +  spinnerIcon: (
Uniformerei questo a `loaderIcon`, per il resto tutto ok.

2020-06-23 10:32 UTC, francescophra approved these changes
LGTM

2020-06-23 10:46 UTC, merged