Added another colour for the tool tip background: brand light
primait/pyxis-npm pull request #45
Opened 2020-09-03 07:51 UTC by VitalyOlegovic

This tool tip background colour is necessary for the domus project.

2020-09-03 08:02 UTC, alessiosantangelo commented
Ciao @VitalyOlegovic in linea generale questo tipo di personalizzazioni dovrebbero essere fatte direttamente sul client che utilizza la particolare forma grafica. In questo specifico caso però hai beccato una mancanza nel nostro design system, quindi bravo :)

2020-09-03 08:03 UTC, alessiosantangelo requested changes

2020-09-03 08:03 UTC, alessiosantangelo commented on src/scss/02_atoms/_tooltips.scss
> +  brandlgt: color(brand, light),
Lo chiamerei semplicemente `brand` anche se usa i colore `brand light`. Infatti non useremo mai il colore `brand` vero e proprio per i tooltips

2020-09-03 08:04 UTC, emanuelemacri commented on src/scss/02_atoms/_tooltips.scss
> +  brandlgt: color(brand, light),
+1 senza fare nuova review

2020-09-03 08:04 UTC, francescophra commented on src/scss/02_atoms/_tooltips.scss
> +  brandlgt: color(brand, light),
@alessiosantangelo sono d'accordo

2020-09-03 08:35 UTC, alessiosantangelo approved these changes

2020-09-03 08:50 UTC, VitalyOlegovic commented
Sì, all'inizio avevo provato a cambiare solo lo sfondo del tool tip, ma rimaneva un rombo blu.

2020-09-07 13:20 UTC, VitalyOlegovic commented
Buonasera @alessiosantangelo mi potresti fare il merge per favore, che non ho i permessi?

2020-09-10 08:21 UTC, merged