Add new rule to download button atoms
primait/pyxis-npm pull request #61
Opened 2021-03-15 16:28 UTC by damjack

CHANGELOG:
- Add new rule `.btn--download__icon--svg` for custom svg icon to **_buttons**

2021-03-17 13:29 UTC, emanuelemacri requested changes

2021-03-17 13:29 UTC, emanuelemacri commented on src/scss/02_atoms/_buttons.scss
> +  left: 20px;
Metti questo valore nella mappa `$downloadButtonConfig` in `rem`.
Oltre questo aggiungi un esempio di utilizzo nel file di test dei bottoni please

2021-03-17 13:30 UTC, alessiosantangelo requested changes

2021-03-17 13:30 UTC, alessiosantangelo commented on src/scss/02_atoms/_buttons.scss
> +.btn--download__icon--svg {
Aggiungerei un esempio nel file `buttons.html`

2021-03-17 13:30 UTC, alessiosantangelo commented on src/scss/02_atoms/_buttons.scss
> +  left: 20px;
`rem(20px)`

2021-03-17 13:56 UTC, emanuelemacri requested changes
Ultima cosetta, poi è ok

2021-03-17 13:56 UTC, emanuelemacri commented on src/scss/02_atoms/_buttons.scss
> +    svgLeft: rem(20px),
solo `left`

2021-03-24 18:04 UTC, emanuelemacri approved these changes, later dismissed

2021-03-31 16:04 UTC, alessiosantangelo approved these changes, later dismissed

2021-04-28 10:03 UTC, eFFeeMMe approved these changes
I ran the tests locally and got no diffs. Good :)

2021-11-15 13:21 UTC, merged